apiVersion: v1
kind: ServiceAccount
metadata:
  name: sun-protect-service-account
  namespace: sun-protect-qa
imagePullSecrets:
  - name: gitlab-sun-protect-pull-token-qa
automountServiceAccountToken: false